[package]
name = "fnp-clipboard-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-rs = "0.1.4"
clipboard = "0.5"
home = "0.5.9"
